 version: "3.7"

 services:
   app:
     image: deploy_debian_buster
     tty: true
     #command: sh -c "yarn install && yarn run dev"
     #command: cmake ../LinVstManager && make -j4
     command: bash
     container_name: con_debian_buster
     hostname: host_debian_buster
     #working_dir: /app
     volumes:
         - ../../../LinVstManager:/home/LinVstManager
     #environment:
       #MYSQL_HOST: mysql
       #MYSQL_USER: root
       #MYSQL_PASSWORD: secret
       #MYSQL_DB: todos
