 version: "3.7"

 services:
   app:
     image: deploy_fedora_34
     tty: true
     #command: sh -c "yarn install && yarn run dev"
     #command: cmake ../LinVstManager && make -j4
     command: ../LinVstManager/test_deploy/build_inside_docker.sh
     container_name: con_fedora_34
     hostname: host_fedora_34
     #working_dir: /app
     volumes:
         - ../../../LinVstManager:/home/LinVstManager
     #environment:
       #MYSQL_HOST: mysql
       #MYSQL_USER: root
       #MYSQL_PASSWORD: secret
       #MYSQL_DB: todos
